feat(vdp): add server plugin to enable SSE streaming and enable endpoints and configuration
instill-ai/api-gateway pull request #202
Opened 2024-06-21 05:24 UTC by tillknuesting

Because:
- KrakenD does not naively support long-lived connections, such as SSE or any other form of streaming.

This commit:
-implement a server plugin for KrakenD that intercepts HTTP requests for the SSE endpoint and connects to the backed-end to transmit data
- adds endpoint and configuration to support streaming

2024-06-21 06:40 UTC, tillknuesting commented
for reference here is the standalone PoC for the plugin: https://github.com/tillknuesting/krakend-streaming

2024-07-02 04:21 UTC, donch1989 commented on config/share/settings-env/input_headers.json
> +    "X-Use-SSE"
We currently use the `Instill-` prefix for our custom headers and should maintain this convention.

2024-07-03 22:56 UTC, donch1989 requested changes

2024-07-03 22:56 UTC, donch1989 commented on config/share/settings-env/input_headers.json
> +    "X-Use-SSE"
Hi @tillknuesting ,
I noticed that you changed the header to `Instill-Use-SSE` in the pipeline-backend, so we need to update it here accordingly.

2024-07-03 22:56 UTC, donch1989 commented on plugins/sse-streaming/main.go
> +		serverURL := fmt.Sprintf("%s%s", backendHost, strings.Replace(backendURLPattern, "{id}", id, 1))
```suggestion
		serverURL := fmt.Sprintf("http://%s%s", backendHost, strings.Replace(backendURLPattern, "{id}", id, 1))
```
I just tried, I guess we need to add `http` here.

2024-07-04 00:28 UTC, donch1989 approved these changes
LGTM

2024-07-04 00:28 UTC, merged